[workspace]

members = [
    "rpcx_protocol",
    "rpcx_derive",
    "rpcx_client",
    "rpcx_server",
    "examples/client_call_mul",
    "examples/client_call_mul_async",
]
 
[profile.release]
debug = true

[profile.bench]
debug = true 