[package]
name = "etcd_xclient_call_mul"
version = "0.1.0"
authors = ["smallnest <smallnest@gmail.com>"]
edition = "2018"

[dependencies]
etcd = "0.9.0" 
rpcx =  { version = "0.2.1", path = "../../../rpcx" }
mul_model =  { version = "0.2.1", path = "../../mul_model" }