[package]
name = "server_mul_protobuf"
version = "0.2.0"
authors = ["smallnest <smallnest@gmail.com>"]
edition = "2018"

[dependencies]
rpcx =  { version = "0.2.0", path = "../../../rpcx" }
mul_model_proto =  { version = "0.2.0", path = "../mul_model_proto" } 