[package]
name = "client_call_proto"
version = "0.3.0"
authors = ["smallnest <smallnest@gmail.com>"]
edition = "2018"
[dependencies]
rpcx =  { version = "0.3.0", path = "../../../rpcx" }
mul_model_proto =  { version = "0.3.0", path = "../mul_model_proto" }