[package]
name = "xclient_call_mul"
version = "0.1.0"
authors = ["smallnest <smallnest@gmail.com>"]
edition = "2018"

[dependencies]
rpcx =  { version = "0.2.0", path = "../../rpcx" }
mul_model =  { version = "0.2.0", path = "../mul_model" }